export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'
export const API_REQUEST_LOG = 'API_REQUEST_LOG'

export const LOCATION_SEARCH = 'LOCATION_SEARCH'
export const LOCATION_SEARCH_DONE = 'LOCATION_SEARCH_DONE'
export const LOCATION_SEARCH_ERROR = 'LOCATION_SEARCH_ERROR'