export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'
export const API_REQUEST_LOG = 'API_REQUEST_LOG'

export const LOCATION_SEARCH = 'BOOK_SEARCH_ADD'
export const LOCATION_SEARCH_DONE = 'BOOK_SEARCH_RETRIVED'
export const LOCATION_SEARCH_ERROR = 'BOOK_SEARCH_CLEAR'